{{- if not .Values.coreConfig.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "takserver.coreConfigSecretName" . }}
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  CoreConfig.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration xmlns="http://bbn.com/marti/xml/config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="CoreConfig.xsd">
        <network multicastTTL="5">
            <input _name="stdssl" protocol="tls" port="{{ .Values.service.ports.cotTls }}" coreVersion="2"/>
            <!-- web connectors -->
            <connector port="{{ .Values.service.ports.https }}" _name="https"/>
            <connector port="{{ .Values.service.ports.fedHttps }}" useFederationTruststore="true" _name="fed_https"/>
            <connector port="{{ .Values.service.ports.certEnroll }}" clientAuth="false" _name="cert_https"/>
        </network>
        <auth>
            <File location="UserAuthenticationFile.xml"/>
        </auth>
        <submission ignoreStaleMessages="false" validateXml="false"/>

        <subscription reloadPersistent="false"/>

        <repository enable="true" numDbConnections="{{ .Values.coreConfig.repository.numDbConnections }}" primaryKeyBatchSize="{{ .Values.coreConfig.repository.primaryKeyBatchSize }}" insertionBatchSize="{{ .Values.coreConfig.repository.insertionBatchSize }}">
          <connection url="jdbc:postgresql://{{ include "takserver.dbHost" . }}:{{ include "takserver.dbPort" . }}/{{ .Values.global.postgresql.auth.database }}" username="{{ .Values.global.postgresql.auth.username }}" password="{{ .Values.global.postgresql.auth.password }}" />
        </repository>

        <repeater enable="true" periodMillis="3000" staleDelayMillis="15000">
            <repeatableType initiate-test="/event/detail/emergency[@type='911 Alert']" cancel-test="/event/detail/emergency[@cancel='true']" _name="911"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Ring The Bell']" cancel-test="/event/detail/emergency[@cancel='true']" _name="RingTheBell"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Geo-fence Breached']" cancel-test="/event/detail/emergency[@cancel='true']" _name="GeoFenceBreach"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Troops In Contact']" cancel-test="/event/detail/emergency[@cancel='true']" _name="TroopsInContact"/>
        </repeater>

        <dissemination smartRetry="false" />

        <filter>
            <flowtag enable="false" text=""/>
            <streamingbroker enable="true"/>
            <scrubber enable="false" action="overwrite"/>
        </filter>

        <buffer>
            <latestSA enable="true"/>
            <queue/>
        </buffer>

        <security>
            <tls context="TLSv1.2"
                keymanager="SunX509"
                keystore="JKS" keystoreFile="/opt/tak/certs/files/takserver.jks" keystorePass="{{ .Values.certs.keystorePassword }}"
                truststore="JKS" truststoreFile="/opt/tak/certs/files/truststore-root.jks" truststorePass="{{ .Values.certs.keystorePassword }}">
            </tls>
        </security>

    {{- if .Values.federation.enabled }}
        <federation allowFederatedDelete="false" allowMissionFederation="true" enableFederation="true">
          <federation-server port="{{ .Values.service.ports.federationV1 }}" v1enabled="true" v2port="{{ .Values.service.ports.federationV2 }}" v2enabled="true">
            <tls context="TLSv1.2"
                keymanager="SunX509"
                keystore="JKS" keystoreFile="/opt/tak/certs/files/takserver.jks" keystorePass="{{ .Values.certs.keystorePassword }}"
                truststore="JKS" truststoreFile="/opt/tak/certs/files/fed-truststore.jks" truststorePass="{{ .Values.certs.keystorePassword }}"/>
          </federation-server>
        </federation>
    {{- end }}
    {{- if .Values.coreConfig.extraXml }}
        {{ .Values.coreConfig.extraXml | nindent 4 }}
    {{- end }}
    </Configuration>
{{- end }}
