apiVersion: v1
kind: Service
metadata:
  name: {{ include "takserver.fullname" . }}
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: cot-tls
      port: {{ .Values.service.ports.cotTls }}
      targetPort: cot-tls
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
    - name: fed-https
      port: {{ .Values.service.ports.fedHttps }}
      targetPort: fed-https
    - name: cert-enroll
      port: {{ .Values.service.ports.certEnroll }}
      targetPort: cert-enroll
    {{- if .Values.federation.enabled }}
    - name: fed-v1
      port: {{ .Values.service.ports.federationV1 }}
      targetPort: fed-v1
    - name: fed-v2
      port: {{ .Values.service.ports.federationV2 }}
      targetPort: fed-v2
    {{- end }}
  selector:
    {{- include "takserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
