{{- if not .Values.coreConfig.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "takserver-cluster.coreConfigSecretName" . }}
  labels:
    {{- include "takserver-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
type: Opaque
stringData:
  CoreConfig.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration xmlns="http://bbn.com/marti/xml/config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="CoreConfig.xsd">
        <network tomcatMaxPool="300" esyncEnableCache="1" multicastTTL="5">
            <input _name="stdssl" protocol="tls" port="{{ .Values.messaging.service.ports.cotTls }}" coreVersion="2"/>
            <!-- web connectors -->
            <connector port="{{ .Values.api.service.ports.https }}" _name="https"/>
            <connector port="{{ .Values.api.service.ports.fedHttps }}" useFederationTruststore="true" _name="fed_https"/>
            <connector port="{{ .Values.api.service.ports.certEnroll }}" clientAuth="false" _name="cert_https"/>
        </network>
        <auth>
            <File location="UserAuthenticationFile.xml"/>
        </auth>
        <submission ignoreStaleMessages="false" validateXml="false"/>

        <subscription reloadPersistent="false"/>

        <repository enable="true" numDbConnections="{{ .Values.coreConfig.repository.numDbConnections }}" primaryKeyBatchSize="{{ .Values.coreConfig.repository.primaryKeyBatchSize }}" insertionBatchSize="{{ .Values.coreConfig.repository.insertionBatchSize }}">
            <connection url="jdbc:postgresql://{{ include "takserver-cluster.dbHost" . }}:{{ include "takserver-cluster.dbPort" . }}/{{ .Values.global.postgresql.auth.database }}" username="{{ .Values.global.postgresql.auth.username }}" password="{{ .Values.global.postgresql.auth.password }}" />
        </repository>

        <repeater connectionPoolAutoSize="false" enable="true" numDbConnections="400" periodMillis="3000" staleDelayMillis="15000">
            <repeatableType initiate-test="/event/detail/emergency[@type='911 Alert']" cancel-test="/event/detail/emergency[@cancel='true']" _name="911"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Ring The Bell']" cancel-test="/event/detail/emergency[@cancel='true']" _name="RingTheBell"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Geo-fence Breached']" cancel-test="/event/detail/emergency[@cancel='true']" _name="GeoFenceBreach"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Troops In Contact']" cancel-test="/event/detail/emergency[@cancel='true']" _name="TroopsInContact"/>
        </repeater>

        <dissemination smartRetry="false" enabled="true"/>

        <filter>
            <flowtag enable="false" text="" />
            <streamingbroker enable="true" />
            <scrubber enable="false" action="overwrite" />
            <qos enabled="false">
                <reportingRateLimiter>
                    <rateLimitRule clientThresholdCount="1000" reportingRateLimitSeconds="120" />
                    <rateLimitRule clientThresholdCount="5000" reportingRateLimitSeconds="180" />
                    <rateLimitRule clientThresholdCount="10000" reportingRateLimitSeconds="240" />
                    <rateLimitRule clientThresholdCount="25000" reportingRateLimitSeconds="480" />
                    <rateLimitRule clientThresholdCount="50000" reportingRateLimitSeconds="960" />
                </reportingRateLimiter>
            </qos>
        </filter>

        <buffer>
            <latestSA enable="true" />
            <queue missionUidLimit="2048" missionContentLimit="2048" />
        </buffer>

        <security>
            <tls context="TLSv1.2"
                keymanager="SunX509"
                keystore="JKS" keystoreFile="/opt/tak/certs/files/takserver.jks" keystorePass="{{ .Values.certs.keystorePassword }}"
                truststore="JKS" truststoreFile="/opt/tak/certs/files/truststore-root.jks" truststorePass="{{ .Values.certs.keystorePassword }}">
            </tls>
        </security>

    {{- if .Values.federation.enabled }}
        <federation allowFederatedDelete="false" allowMissionFederation="true" enableFederation="true">
          <federation-server port="{{ .Values.messaging.service.ports.federationV1 }}" v1enabled="true" v2port="{{ .Values.messaging.service.ports.federationV2 }}" v2enabled="true">
            <tls context="TLSv1.2"
                keymanager="SunX509"
                keystore="JKS" keystoreFile="/opt/tak/certs/files/takserver.jks" keystorePass="{{ .Values.certs.keystorePassword }}"
                truststore="JKS" truststoreFile="/opt/tak/certs/files/fed-truststore.jks" truststorePass="{{ .Values.certs.keystorePassword }}"/>
          </federation-server>
        </federation>
    {{- end }}

    {{- if or .Values.nats.enabled .Values.cluster.natsUrl }}
        <cluster enabled="true" kubernetes="true" natsClusterID="{{ .Values.cluster.natsClusterId }}" natsURL="{{ include "takserver-cluster.natsUrl" . }}"/>
    {{- end }}
    {{- if .Values.coreConfig.extraXml }}
        {{ .Values.coreConfig.extraXml | nindent 4 }}
    {{- end }}
    </Configuration>
{{- end }}
