{{- if and (not .Values.postgresql.enabled) (not .Values.database.existingSecret) (not .Values.global.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "takserver-cluster.fullname" . }}-db
  labels:
    {{- include "takserver-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  {{ .Values.database.existingSecretPasswordKey }}: {{ .Values.global.postgresql.auth.password | quote }}
{{- end }}
