apiVersion: v1
kind: Service
metadata:
  name: {{ include "takserver-cluster.fullname" . }}-api
  labels:
    {{- include "takserver-cluster.componentLabels" (dict "context" $ "component" "api") | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: https
      port: {{ .Values.api.service.ports.https }}
      targetPort: https
    - name: fed-https
      port: {{ .Values.api.service.ports.fedHttps }}
      targetPort: fed-https
    - name: cert-enroll
      port: {{ .Values.api.service.ports.certEnroll }}
      targetPort: cert-enroll
  selector:
    {{- include "takserver-cluster.componentSelectorLabels" (dict "context" $ "component" "api") | nindent 4 }}
